import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
// import DashboardPage from './dashboard/page';
import Layout from './dashboard/layout';
import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs';
import { Home } from './Home';

export default function RootLayout() {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <Home />
            </SignedOut>
            <SignedIn>
              <Layout />
            </SignedIn>
          </header>
        </body>
      </html>
    </ClerkProvider>
  );
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};