import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import './globals.css';
import { Home } from './Home';
import Dashboard from './dashboard/page';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider
    appearance={{
      layout: {
        socialButtonsPlacement: 'bottom',
        socialButtonsVariant: 'iconButton',
        termsPageUrl: 'https://clerk.com/terms',
        animations:true
      }
    }}
    >
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              {/* <SignInButton /> */}
              <Home />
            </SignedOut>
            <SignedIn>
              {/* Render the children component (which should be the Dashboard component) */}
              <UserButton />
              <Dashboard />
            </SignedIn>
          </header>
          {/* <main>{children}</main> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};