import React from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import './globals.css';
import { Home } from './Home';
import DashboardPage from './(routes)/dashboard/dashboardPage';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              {/* <SignInButton /> */}
              <Home />
            </SignedOut>
            <SignedIn>
              {/* <UserButton /> */}
              <DashboardPage />
            </SignedIn>
          </header>
          {/* <main>{children}</main> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};